nav:
    - Home: index.md
    - Guide: Guide
    - Chapter-1-Introduction: Chapter-1-Introduction
    - Chapter-2-A-Simple-Syntax-Directed-Translator: Chapter-2-A-Simple-Syntax-Directed-Translator
    - Chapter-3-Lexical-Analysis: Chapter-3-Lexical-Analysis
    - Chapter-4-Syntax-Analysis: Chapter-4-Syntax-Analysis
    - Chapter-5-Syntax-Directed-Translation: Chapter-5-Syntax-Directed-Translation
    - Chapter-6-Intermediate-Code-Generation: Chapter-6-Intermediate-Code-Generation
    - Chapter-7-Run-Time-Environments: Chapter-7-Run-Time-Environments
    - Chapter-9-Machine-Independent-Optimizations: Chapter-9-Machine-Independent-Optimizations