nav:
    - Home: index.md
    - Chapter1: Chapter1-Introduction
    - Chapter2: Chapter2-A-Simple-Syntax-Directed-Translator
    - Chapter3: Chapter3-Lexical-Analysis
    - Chapter4: Chapter4-Syntax-Analysis
    - Chapter5: Chapter5-Syntax-Directed-Translation
    - Chapter6: Chapter6-Intermediate-Code-Generation
    - Chapter7: Chapter7-Run-Time-Environments
    - Chapter9: Chapter9-Machine-Independent-Optimizations