nav:
    - 7: index.md
    - 7.1-Storage-Organization: 7.1-Storage-Organization.md
    - 7.2-Stack-Allocation-of-Space: 7.2-Stack-Allocation-of-Space.md
    - 7.3-Access-to-Non-local-Data-on-the-Stack: 7.3-Access-to-Non-local-Data-on-the-Stack.md
    - 7.4-Heap-Management: 7.4-Heap-Management.md