nav:
    - Introduction: index.md
    - Compile-time-and-run-time: Compile-time-and-run-time.md
    - VS-LL-parser-VS-LR-parser: VS-LL-parser-VS-LR-parser.md
    - Parsing-algorithm: Parsing-algorithm
    - Parser-generator: Parser-generator
    - Bind: Bind
    - Symbol-table: Symbol-table.md