nav:
    - Introduction: index.md
    - Basic-block: Basic-block
    - Static-single-assignment-form: Static-single-assignment-form
    - Control-flow-analysis: Control-flow-analysis
    - Data-flow-analysis: Data-flow-analysis
    - Inline: Inline    