nav:
    - 3: index.md
    - 3.1-The-Role-of-the-Lexical-Analyzer: 3.1-The-Role-of-the-Lexical-Analyzer
    - 3.3-Specication-of-Tokens: 3.3-Specication-of-Tokens
    - 3.4-Recognition-of-Tokens: 3.4-Recognition-of-Tokens
    - 3.6-Finite-Automata: 3.6-Finite-Automata
    - 3.7-From-Regular-Expressions-to-Automata: 3.7-From-Regular-Expressions-to-Automata
