nav:
    - 4: index.md
    - 4.2-Context-Free-Grammars: 4.2-Context-Free-Grammars
    - 4.3-Writing-a-Grammar: 4.3-Writing-a-Grammar
    - 4.5-Bottom-Up-Parsing: 4.5-Bottom-Up-Parsing
    - 4.6-Introduction-to-LR-Parsing-Simple-LR: 4.6-Introduction-to-LR-Parsing-Simple-LR
    - 4.7-More-Powerful-LR-Parsers: 4.7-More-Powerful-LR-Parsers
    
    