nav:
    - Home: index.md
    - Chapter1-Introduction: Chapter1-Introduction
    - Chapter2-A-Simple-Syntax-Directed-Translator: Chapter2-A-Simple-Syntax-Directed-Translator
    - Chapter3-Lexical-Analysis: Chapter3-Lexical-Analysis
    - Chapter4-Syntax-Analysis: Chapter4-Syntax-Analysis
    - Chapter5-Syntax-Directed-Translation: Chapter5-Syntax-Directed-Translation
    - Chapter6-Intermediate-Code-Generation: Chapter6-Intermediate-Code-Generation
    - Chapter7-Run-Time-Environments: Chapter7-Run-Time-Environments
    - Chapter9-Machine-Independent-Optimizations: Chapter9-Machine-Independent-Optimizations